### PR TITLE
Tests update

### PR DESCRIPTION
**Pull request by vbuberen**
This PR updates tests to be less flaky, fixes some typos and adds a new changelog entry.

After my previous PR merge I saw that tests failed https://github.com/dinko-pehar/mock_data/runs/2619656817 
In logs we can see that it was due to one of `mockLocation` tests having some conditions which aren't really guaranteed to always get the same result. So I fixed it.

Along with that I found a few small typos in tests names, etc.

@dinko-pehar Could you also let me know if you plan to release a null-safety update to `pub.dev`? Would be good to have it sort of `officially` available to projects, like the one I am currently working on.

### CODE REVIEW

**Comment by dinkopehar** [comment]
Hey @vbuberen 

Thank you again for contributing. Yeah, I saw some tests failed but didnt find time to explore mockLocation since it isn't a feature I created.
I will try to release it tomorrow I hope.
Has everything set up for v2 by the looks of it ?

**Comment by vbuberen** [comment]
I don't really know about your roadmap, but I think that yes, everything is ready for v2, since the main reason for major version bump is null safety migration.

I would improve tests as you suggested in #7, but it can be done later as not really influences the package at the moment.

**Comment by dinkopehar** [comment]
Tests pass and it's merged into `master` . I'll release this tomorrow and notify you here.

**Comment by dinkopehar** [comment]
@vbuberen  It's released :tada: :rocket: 
Thank you for your help and for using it in first place. If you have any questions, feel free to ask.

**Comment by vbuberen** [comment]
Thank you as well for creating it in the first place.

**Pull request merged**
