### PR TITLE
Added new color spaces, names and minor bug fix mockname

### PR DESCRIPTION
**Pull request by nbodepudi**
Changed the function for throwing exception in mockName funciton.
In mockName.
> !('female'.contains(gender))

cannot be used as then they can input some random words like mal, fem, emal etc
Added 35 names in male set and female set. 
Added 3 new color spaces in mockColor functions. I added those in README.md file.
Will added test cases other soon.

### CODE REVIEW

**Comment by dinkopehar** [comment]
Great :smile: . I will chech this later and do necessery things and after merge I will add you to contributors list. Also, congratulations on your first pull request :+1:

**Comment by nbodepudi** [comment]
Thanks😁, okay cool.

**Comment by nbodepudi** [comment]
I have added support for generating IPv6 addresses. I thought it would be a nice addition. Added few checks for IPv4 input. Check the changes.

**Comment by dinkopehar** [comment]
Sorry I wasn't free yestarday. I will check it tonight, but diffinetly will merge. It's nice what you added for all color models and names and IPs

**Comment by dinkopehar** [comment]
Hi. I checked all your changes and they are good, but can you follow these steps for IPv6:
- Rename file `mock_ipv4` in `src` to `mock_ip`.
- In that file you can place functions for IPs generate.
- And in `mock_data` file export that file instead of `mock_ipv4`

Then I can merge ? I'll do additional for documentation changes for documentation.

**Comment by nbodepudi** [comment]
Done those changes, check now.

**Comment by dinkopehar** [comment]
I'll merge now and add you to contributors list. Congrats :smile:

**Pull request merged**
